/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jnr;
import jnr.ffi.Pointer;
import jnr.ffi.types.u_int32_t;
import jnr.ffi.LibraryLoader;
import jnr.ffi.Runtime;


public class App {
    public interface LibLoro{
        Pointer loro_new();
        void loro_free(Pointer loro);
        Pointer loro_get_text(Pointer loro, String id);
        void text_free(Pointer text);
        void text_insert(Pointer text, Pointer ctx, @u_int32_t long pos, String value);
        String text_value(Pointer text);
    }

    public static void main(String[] args) {
        LibLoro libLoro = LibraryLoader.create(LibLoro.class).load("loro");
        var loro = libLoro.loro_new();
        var text = libLoro.loro_get_text(loro, "text");
        // var pos = Pointer.wrap(u_int32_t.class, 0);
        libLoro.text_insert(text, loro, 0, "abc");
        var value = libLoro.text_value(text);
        System.out.println(value);
        libLoro.text_free(text);
        libLoro.loro_free(loro);
    }
}
