import { readFileSync } from "node:fs";
import { expect, it } from "vitest";
import { LoroDoc, VersionVector, type Frontiers } from "../bundler/index";

// Generated by the public Rust regression with LORO_HISTORY_FIXTURE set to this
// absolute path. The first peer-1 block is halved and both checksums are repaired.
const snapshot = readFileSync(
  new URL("./fixtures/unparsable-history.snapshot.bin", import.meta.url),
);
const mid: Frontiers = [{ peer: "1", counter: 1 }];
const remote = new LoroDoc();
remote.setPeerId(9);
remote.getText("text").insert(0, "concurrent");
const updates = remote.export({ mode: "update" });
const json = remote.exportJsonUpdates();

const readers: Record<string, (doc: LoroDoc) => unknown> = {
  checkout: (doc) => doc.checkout(mid),
  diff: (doc) => doc.diff(mid, doc.oplogFrontiers()),
  revertTo: (doc) => doc.revertTo(mid),
  import: (doc) => doc.import(updates),
  importBatch: (doc) => doc.importBatch([updates, updates]),
  importJsonUpdates: (doc) => doc.importJsonUpdates(json),
  forkAt: (doc) => doc.forkAt(mid),
  findIdSpansBetween: (doc) =>
    doc.findIdSpansBetween(mid, doc.oplogFrontiers()),
  frontiersToVV: (doc) => doc.frontiersToVV(mid),
  vvToFrontiers: (doc) => {
    const vv = new VersionVector(doc.oplogVersion().toJSON());
    vv.setEnd({ peer: "1", counter: 2 });
    return doc.vvToFrontiers(vv);
  },
  travelChangeAncestors: (doc) => doc.travelChangeAncestors(mid, () => true),
  getChangeAt: (doc) => doc.getChangeAt(mid[0]),
  getChangeAtLamport: (doc) => doc.getChangeAtLamport("1", 1),
  getOpsInChange: (doc) => doc.getOpsInChange(mid[0]),
  getChangedContainersIn: (doc) => doc.getChangedContainersIn(mid[0], 1),
  cmpFrontiers: (doc) => doc.cmpFrontiers(mid, doc.oplogFrontiers()),
  exportUpdates: (doc) => doc.export({ mode: "update" }),
  exportUpdatesInRange: (doc) =>
    doc.export({
      mode: "updates-in-range",
      spans: [{ id: mid[0], len: 1 }],
    }),
  exportShallow: (doc) =>
    doc.export({ mode: "shallow-snapshot", frontiers: mid }),
};

for (const [name, read] of Object.entries(readers)) {
  it(`${name} rejects its first unreadable block without trapping WASM`, () => {
    const doc = new LoroDoc();
    doc.import(snapshot);
    const value = doc.toJSON();
    const frontiers = doc.frontiers();
    const vv = doc.oplogVersion().toJSON();
    let events = 0;
    doc.subscribe(() => events++);
    expect(() => read(doc)).toThrow(/cannot parse change block/);
    expect(doc.toJSON()).toEqual(value);
    expect(doc.frontiers()).toEqual(frontiers);
    expect(doc.oplogVersion().toJSON()).toEqual(vv);
    expect(doc.isDetached()).toBe(false);
    expect(events).toBe(0);
    expect(() => doc.checkout(frontiers)).toThrow(/cannot parse change block/);
    // A fresh document in the same module still works: no WASM trap occurred.
    const healthy = new LoroDoc();
    healthy.getText("text").insert(0, "usable");
    expect(healthy.toJSON()).toEqual({ text: "usable" });
  });
}
