build:
  cargo build

test:
  cargo nextest run

# test without proptest
test-fast:
  RUSTFLAGS='--cfg no_proptest' cargo nextest run

check-unsafe:
  env RUSTFLAGS="-Funsafe-code --cap-lints=warn" cargo check

deny:
  cargo deny check

crev:
  cargo crev crate check

fuzz-yata-long:
  cargo fuzz run yata -- -max_total_time=300 -max_len=4000 -jobs=2

quick-fuzz:
  cargo fuzz run single_client_text -- -max_total_time=10 -max_len=1000 & 
  cargo fuzz run yata -- -max_total_time=10 -max_len=1000 & 
  cargo fuzz run two_client_text -- -max_total_time=10 -max_len=1000

flame:
  cargo flamegraph --example test --features=fuzzing --root
