
# cargo-vet audits file

[[audits.arref]]
who = "Zixuan Chen <remch183@outlook.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "I'm the author of this crate"

[[audits.color-backtrace]]
who = "Zixuan Chen <remch183@outlook.com>"
criteria = "safe-to-run"
version = "0.5.1"

[[audits.crdt-list]]
who = "Zixuan Chen <remch183@outlook.com>"
criteria = "safe-to-deploy"
version = "0.1.3"
notes = "I'm the author of this crate"

[[audits.ctor]]
who = "Zixuan Chen <remch183@outlook.com>"
criteria = "safe-to-run"
version = "0.1.23"

[[audits.fxhash]]
who = "Zixuan Chen <remch183@outlook.com>"
criteria = "safe-to-deploy"
version = "0.2.1"

[[audits.num]]
who = "Zixuan Chen <remch183@outlook.com>"
criteria = "safe-to-deploy"
version = "0.4.0"

[[audits.ouroboros]]
who = "Zixuan Chen <remch183@outlook.com>"
criteria = "safe-to-deploy"
version = "0.15.5"

