/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Loro {
  constructor()
  getText(id: string): LoroText
}
export class LoroText {
  insert(loro: Loro, pos: number, text: string): void
  value(): string
}
