name: Publish to Crates.io

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'chore: release rust crates v')
    steps:
      - uses: actions/checkout@v4

      - name: Extract release flags
        id: extract_flags
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          EXCLUDED_FLAGS=$(echo "$PR_BODY" | grep -o '<!-- RELEASE_FLAGS: .* -->' | sed 's/<!-- RELEASE_FLAGS: \(.*\) -->/\1/')
          echo "EXCLUDED_FLAGS=$EXCLUDED_FLAGS" >> $GITHUB_OUTPUT

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "${{ steps.extract_flags.outputs.EXCLUDED_FLAGS }}"
          cargo install cargo-release
          cargo release publish --workspace ${{ steps.extract_flags.outputs.EXCLUDED_FLAGS }} --execute --no-confirm
          cargo release tag --workspace ${{ steps.extract_flags.outputs.EXCLUDED_FLAGS }} --execute --no-confirm
          git push --tags